module.exports = [
    "concurrently",
    "graphql",
    "lodash",
    "apollo-server-express",
    "bcryptjs",
    "cloudinary",
    "cors",
    "dotenv",
    "esm",
    "express",
    "jsonwebtoken",
    "mongoose",
    "nodemailer",
    "uuid",
    "nodemon",
    "jwt-decode",
]